# Generated by Django 6.0.7 on 2026-07-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instruction",
            name="action",
            field=models.CharField(
                choices=[
                    ("click", "Click"),
                    ("javascript", "Javascript"),
                    ("tabs", "Tabs"),
                ],
                max_length=16,
            ),
        ),
    ]
