services:
  acob-srv:
    build: .
    expose:
      - "58347"
    environment:
      ACOB_DATA_DIR: /data
      ACOB_SRV_HOST: 0.0.0.0
      ACOB_SRV_PORT: 58347
    volumes:
      - srv-data:/data
    networks:
      - acob

networks:
  acob: {}

volumes:
  srv-data: {}
