-- ACOB Postgres init script.
-- Nothing custom is required: the official postgres image creates
-- the database and role from the environment on first start
-- (compose maps ACOB_DATABASE_PORTGRES_* to its POSTGRES_* variables),
-- and Django creates all tables via `manage.py migrate`.
-- Keep this file as a placeholder for future extensions
-- (e.g. CREATE EXTENSION ...). It runs once on volume init
-- from /docker-entrypoint-initdb.d/.
