# Generated by Django 6.0.7 on 2026-09-06 18:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('batch', 'Batch'), ('cleanup', 'Cleanup'), ('click', 'Click'), ('close', 'Close'), ('console', 'Console'), ('focus', 'Focus'), ('javascript', 'Javascript'), ('keyboard', 'Keyboard'), ('list', 'List'), ('navigate', 'Navigate'), ('proxy', 'Proxy'), ('record', 'Record'), ('reload', 'Reload'), ('screenshot', 'Screenshot'), ('scroll', 'Scroll')], max_length=16)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reinstall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
