# Generated by Django 6.0.7 on 2026-08-02 07:23

import api.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExtensionReload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bid",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[api.validators.validate_bid],
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bid",
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        validators=[api.validators.validate_bid],
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("click", "Click"),
                            ("close", "Close"),
                            ("focus", "Focus"),
                            ("javascript", "Javascript"),
                            ("keyboard", "Keyboard"),
                            ("list", "List"),
                            ("navigate", "Navigate"),
                            ("reload", "Reload"),
                            ("screenshot", "Screenshot"),
                            ("scroll", "Scroll"),
                        ],
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bid",
                    models.CharField(
                        db_index=True,
                        max_length=32,
                        validators=[api.validators.validate_bid],
                    ),
                ),
                ("tid", models.PositiveBigIntegerField()),
                ("data", models.TextField()),
                ("content_type", models.CharField(default="image/png", max_length=32)),
                ("full_page", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
