# Generated by Django 6.0.7 on 2026-08-12 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Screenshot",
        ),
    ]
