# Generated by Django 6.0.7 on 2026-09-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instruction',
            name='bid',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
