# Generated by Django 6.0.7 on 2026-09-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_instruction_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='action',
            field=models.CharField(choices=[('batch', 'Batch'), ('cleanup', 'Cleanup'), ('click', 'Click'), ('close', 'Close'), ('console', 'Console'), ('focus', 'Focus'), ('javascript', 'Javascript'), ('keyboard', 'Keyboard'), ('list', 'List'), ('navigate', 'Navigate'), ('proxy', 'Proxy'), ('record', 'Record'), ('reload', 'Reload'), ('screenshot', 'Screenshot'), ('scroll', 'Scroll'), ('wait', 'Wait')], max_length=16),
        ),
    ]
