# Generated by Django 6.0.7 on 2026-08-12 20:44

from django.db import migrations, models

import api.validators


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_delete_screenshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowserHeartbeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bid",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        validators=[api.validators.validate_bid],
                    ),
                ),
                ("settings", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name="instruction",
            name="action",
            field=models.CharField(
                choices=[
                    ("click", "Click"),
                    ("close", "Close"),
                    ("focus", "Focus"),
                    ("javascript", "Javascript"),
                    ("keyboard", "Keyboard"),
                    ("list", "List"),
                    ("navigate", "Navigate"),
                    ("record_start", "Record Start"),
                    ("record_stop", "Record Stop"),
                    ("reload", "Reload"),
                    ("screenshot", "Screenshot"),
                    ("scroll", "Scroll"),
                ],
                max_length=16,
            ),
        ),
    ]
