# Generated by Django 6.0.7 on 2026-08-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_browserheartbeat_alter_instruction_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instruction",
            name="action",
            field=models.CharField(
                choices=[
                    ("batch", "Batch"),
                    ("click", "Click"),
                    ("close", "Close"),
                    ("focus", "Focus"),
                    ("javascript", "Javascript"),
                    ("keyboard", "Keyboard"),
                    ("list", "List"),
                    ("navigate", "Navigate"),
                    ("record_start", "Record Start"),
                    ("record_stop", "Record Stop"),
                    ("reload", "Reload"),
                    ("screenshot", "Screenshot"),
                    ("scroll", "Scroll"),
                ],
                max_length=16,
            ),
        ),
    ]
