# Generated by Django 6.0.7 on 2026-09-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_instruction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='action',
            field=models.CharField(choices=[('batch', 'Batch'), ('click', 'Click'), ('close', 'Close'), ('focus', 'Focus'), ('javascript', 'Javascript'), ('keyboard', 'Keyboard'), ('list', 'List'), ('navigate', 'Navigate'), ('proxy', 'Proxy'), ('record', 'Record'), ('reload', 'Reload'), ('screenshot', 'Screenshot'), ('scroll', 'Scroll')], max_length=16),
        ),
    ]
